# BEGIN project-specific configuration

.fip_api: &fip_api
  variables:
    DOCKERFILE: "fip_api/Dockerfile"
    IMAGE_NAME: "fip-api"
    PACKAGE: "fip_api"
  only:
    changes:
      - "fip_api/**/*"

# END project-specific configuration

# BEGIN actual pipeline definition

# rust_build

build_1:fip_api:
  dependencies: []
  extends:
    - ".build"
    - ".fip_api"
    - ".target_1"

upload_1:fip_api:
  dependencies:
    - "build_1:fip_api"
  extends:
    - ".fip_api"
    - ".target_1"
    - ".upload"
  needs:
    - "build_1:fip_api"
    # - "build_2:fip_api"
    # - "build_3:fip_api"

build_2:fip_api:
  dependencies: []
  extends:
    - ".build"
    - ".fip_api"
    - ".target_2"

upload_2:fip_api:
  dependencies:
    - "build_2:fip_api"
  extends:
    - ".fip_api"
    - ".target_2"
    - ".upload"
  needs:
    # - "build_1:fip_api"
    - "build_2:fip_api"
    # - "build_3:fip_api"

build_3:fip_api:
  dependencies: []
  extends:
    - ".build"
    - ".fip_api"
    - ".target_3"

upload_3:fip_api:
  dependencies:
    - "build_3:fip_api"
  extends:
    - ".fip_api"
    - ".target_3"
    - ".upload"
  needs:
    # - "build_1:fip_api"
    # - "build_2:fip_api"
    - "build_3:fip_api"

release:fip_api:
  dependencies: []
  extends:
    - ".release"
    - ".fip_api"
  needs:
    # - "upload_1:fip_api"
    # - "upload_2:fip_api"
    - "upload_3:fip_api"

test:fip_api:
  dependencies: []
  extends:
    - ".test"
    - ".fip_api"
  # needs:
  #   - "build:fip_api"

coverage:fip_api:
  dependencies:
    - "test:fip_api"
  extends:
    - ".coverage"
    - ".fip_api"
  needs:
    - "test:fip_api"

deploy:fip_api:
  dependencies: []
  extends:
    - ".deploy"
    - ".fip_api"
  needs:
    - "test:fip_api"

# END actual pipeline definition
